### ISSUE TITLE
Forward des messages

### ISSUE THREAD

**Issue by zeecho** [gagou9/maischalbot#1]
Quand on fait un forward d'un message, ça le reposte avec juste le nom de la personne qui a forward. On ne sait pas du tout qui a écrit le message à l'origine

**Comment by gagou9** [comment]
Aie.
On parle bien de forward, pas de reply hein?

**Comment by gagou9** [comment]
should be fixed in [#62b4614](https://github.com/gagou9/maischalbot/commit/62b461472d2eb769c5f5536952f7bfb823f9a63a)
